---
name: Java CI

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [8, 11, 17, 21]
      fail-fast: false
      max-parallel: 4
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Test with Maven
        run: mvn package -P release -B --file pom.xml
      - name: Attach Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1
      - name: Attach distribution
        uses: actions/upload-artifact@v4
        with:
          name: jfreechart-dist
          path: |
            target/apidocs
            target/maven-repo

...
