---
name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test with JDK 17 on ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Build and Test with Maven
        run: mvn package -P release -B --file pom.xml
      - name: Attach Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1
      - name: Attach distribution
        uses: actions/upload-artifact@v4
        with:
          name: jfreechart-dist
          path: |
            target/apidocs
            target/maven-repo
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/jfreechart-*-dist.zip
